//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: com.mango.protocol.enum.proto
namespace com.mango.protocol.Enum
{
    [global::ProtoBuf.ProtoContract(Name=@"PushWindowType")]
    public enum PushWindowType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"WINDOW_CLOSE", Value=0)]
      WINDOW_CLOSE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WINDOW_1x1", Value=1)]
      WINDOW_1x1 = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WINDOW_2x2", Value=2)]
      WINDOW_2x2 = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WINDOW_3x3", Value=3)]
      WINDOW_3x3 = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WINDOW_3x4", Value=4)]
      WINDOW_3x4 = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WINDOW_3x5", Value=5)]
      WINDOW_3x5 = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Protocol")]
    public enum Protocol
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_KEEPALIVE", Value=256)]
      CS_KEEPALIVE = 256,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SC_KEEPALIVE", Value=257)]
      SC_KEEPALIVE = 257,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_LOGIN", Value=258)]
      CS_LOGIN = 258,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SC_LOGIN", Value=259)]
      SC_LOGIN = 259,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_LOGOUT", Value=260)]
      CS_LOGOUT = 260,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SC_LOGOUT", Value=261)]
      SC_LOGOUT = 261,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SC_ALARM", Value=276)]
      SC_ALARM = 276,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_GETUNCONFIRMEDALARM", Value=277)]
      CS_GETUNCONFIRMEDALARM = 277,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SC_GETUNCONFIRMEDALARM", Value=278)]
      SC_GETUNCONFIRMEDALARM = 278,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SC_GETALARMLIST", Value=279)]
      SC_GETALARMLIST = 279,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_CONFIRMALARMBYCODE", Value=280)]
      CS_CONFIRMALARMBYCODE = 280,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_CONFIRMALARM", Value=281)]
      CS_CONFIRMALARM = 281,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SC_CONFIRMALARM", Value=282)]
      SC_CONFIRMALARM = 282,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_HASTENHANDLE", Value=283)]
      CS_HASTENHANDLE = 283,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SC_HASTENHANDLE", Value=284)]
      SC_HASTENHANDLE = 284,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_SENDSMS", Value=285)]
      CS_SENDSMS = 285,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SC_SENDSMS", Value=286)]
      SC_SENDSMS = 286,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_PINKONG", Value=287)]
      CS_PINKONG = 287,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SC_PINKONG", Value=288)]
      SC_PINKONG = 288,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_LUNXUN", Value=289)]
      CS_LUNXUN = 289,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SC_LUNXUN", Value=290)]
      SC_LUNXUN = 290,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_ACCESSCONTROl", Value=291)]
      CS_ACCESSCONTROl = 291,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SC_ACCESSCONTROL", Value=292)]
      SC_ACCESSCONTROL = 292
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ALARM_STATE")]
    public enum ALARM_STATE
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TEST", Value=0)]
      TEST = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NEW", Value=1)]
      NEW = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ADEVICE_ERROR", Value=2)]
      ADEVICE_ERROR = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CONFIRMED_AS_MISTAKE", Value=3)]
      CONFIRMED_AS_MISTAKE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CONFIRMED_AS_REAL", Value=4)]
      CONFIRMED_AS_REAL = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIXED", Value=10)]
      FIXED = 10
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Pinkongtype")]
    public enum Pinkongtype
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SetWindow", Value=1)]
      SetWindow = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SetCamera", Value=2)]
      SetCamera = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CloseWindow", Value=3)]
      CloseWindow = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetOutput", Value=4)]
      GetOutput = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SaveScene", Value=5)]
      SaveScene = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SwitchScene", Value=6)]
      SwitchScene = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CloseAll", Value=7)]
      CloseAll = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetWindows", Value=8)]
      GetWindows = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SetScene", Value=9)]
      SetScene = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SetOutput", Value=10)]
      SetOutput = 10
    }
  
}