//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: com.mango.protocol.enum.proto
namespace com.mango.protocol.Enum
{
    [global::ProtoBuf.ProtoContract(Name=@"PushWindowType")]
    public enum PushWindowType
    {           
      [global::ProtoBuf.ProtoEnum(Name=@"WINDOW_CLOSE", Value=0)]
      WINDOW_CLOSE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WINDOW_1x1", Value=1)]
      WINDOW_1x1 = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WINDOW_2x2", Value=2)]
      WINDOW_2x2 = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WINDOW_3x3", Value=3)]
      WINDOW_3x3 = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WINDOW_3x4", Value=4)]
      WINDOW_3x4 = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WINDOW_3x5", Value=5)]
      WINDOW_3x5 = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Protocol")]
    public enum Protocol
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_KEEPALIVE", Value=256)]
      CS_KEEPALIVE = 256,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SC_KEEPALIVE", Value=257)]
      SC_KEEPALIVE = 257,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_LOGIN", Value=258)]
      CS_LOGIN = 258,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SC_LOGIN", Value=259)]
      SC_LOGIN = 259,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_LOGOUT", Value=260)]
      CS_LOGOUT = 260,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SC_LOGOUT", Value=261)]
      SC_LOGOUT = 261,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SC_ALARM", Value=276)]
      SC_ALARM = 276
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ALARM_STATE")]
    public enum ALARM_STATE
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TEST", Value=0)]
      TEST = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NEW", Value=1)]
      NEW = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ADEVICE_ERROR", Value=2)]
      ADEVICE_ERROR = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CONFIRMED_AS_MISTAKE", Value=3)]
      CONFIRMED_AS_MISTAKE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CONFIRMED_AS_REAL", Value=4)]
      CONFIRMED_AS_REAL = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIXED", Value=10)]
      FIXED = 10
    }
  
}