//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using com.mango.protocol.Enum;
   
// Generated from: com.mango.protocol.msg.message.proto
// Note: requires additional types generated from: com.mango.protocol.enum.proto
namespace com.mango.protocol.msg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ClientConfig")]
  public partial class ClientConfig : global::ProtoBuf.IExtensible
  {
    public ClientConfig() {}
    
    private bool _pushEnabled = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pushEnabled", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool pushEnabled
    {
      get { return _pushEnabled; }
      set { _pushEnabled = value; }
    }
    private PushWindowType _type = PushWindowType.WINDOW_CLOSE;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(PushWindowType.WINDOW_CLOSE)]
    public PushWindowType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _subscribe = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(3, Name=@"subscribe", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> subscribe
    {
      get { return _subscribe; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_KeepAlive")]
  public partial class CS_KeepAlive : global::ProtoBuf.IExtensible
  {
    public CS_KeepAlive() {}
    
    private Protocol _protocol = Protocol.CS_KEEPALIVE;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"protocol", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Protocol.CS_KEEPALIVE)]
    public Protocol protocol
    {
      get { return _protocol; }
      set { _protocol = value; }
    }
    private long _datetime = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"datetime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long datetime
    {
      get { return _datetime; }
      set { _datetime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_KeepAlive")]
  public partial class SC_KeepAlive : global::ProtoBuf.IExtensible
  {
    public SC_KeepAlive() {}
    
    private Protocol _protocol = Protocol.SC_KEEPALIVE;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"protocol", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Protocol.SC_KEEPALIVE)]
    public Protocol protocol
    {
      get { return _protocol; }
      set { _protocol = value; }
    }
    private long _datetime = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"datetime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long datetime
    {
      get { return _datetime; }
      set { _datetime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_LOGIN")]
  public partial class CS_LOGIN : global::ProtoBuf.IExtensible
  {
    public CS_LOGIN() {}
    
    private Protocol _protocol = Protocol.CS_LOGIN;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"protocol", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Protocol.CS_LOGIN)]
    public Protocol protocol
    {
      get { return _protocol; }
      set { _protocol = value; }
    }
    private string _username = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }
    private string _password = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private string _sessionId = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sessionId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sessionId
    {
      get { return _sessionId; }
      set { _sessionId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_LOGIN")]
  public partial class SC_LOGIN : global::ProtoBuf.IExtensible
  {
    public SC_LOGIN() {}
    
    private Protocol _protocol = Protocol.SC_LOGIN;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"protocol", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Protocol.SC_LOGIN)]
    public Protocol protocol
    {
      get { return _protocol; }
      set { _protocol = value; }
    }
    private com.mango.protocol.msg.ClientConfig _client = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"client", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.mango.protocol.msg.ClientConfig client
    {
      get { return _client; }
      set { _client = value; }
    }
    private int _ret = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ret", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ret
    {
      get { return _ret; }
      set { _ret = value; }
    }
    private string _username = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }
    private int _userId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private com.mango.protocol.msg.ClientConfig _config = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"config", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.mango.protocol.msg.ClientConfig config
    {
      get { return _config; }
      set { _config = value; }
    }
    private string _sessionId = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"sessionId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sessionId
    {
      get { return _sessionId; }
      set { _sessionId = value; }
    }
    private string _module = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"module", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string module
    {
      get { return _module; }
      set { _module = value; }
    }
    private string _sid = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"sid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sid
    {
      get { return _sid; }
      set { _sid = value; }
    }
    private int _flag = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int flag
    {
      get { return _flag; }
      set { _flag = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_LOGOUT")]
  public partial class CS_LOGOUT : global::ProtoBuf.IExtensible
  {
    public CS_LOGOUT() {}
    
    private Protocol _protocol = Protocol.CS_LOGOUT;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"protocol", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Protocol.CS_LOGOUT)]
    public Protocol protocol
    {
      get { return _protocol; }
      set { _protocol = value; }
    }
    private string _sessionId = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sessionId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sessionId
    {
      get { return _sessionId; }
      set { _sessionId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_LOGOUT")]
  public partial class SC_LOGOUT : global::ProtoBuf.IExtensible
  {
    public SC_LOGOUT() {}
    
    private Protocol _protocol = Protocol.SC_LOGOUT;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"protocol", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Protocol.SC_LOGOUT)]
    public Protocol protocol
    {
      get { return _protocol; }
      set { _protocol = value; }
    }
    private int _ret = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ret", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ret
    {
      get { return _ret; }
      set { _ret = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_Alarm")]
  public partial class SC_Alarm : global::ProtoBuf.IExtensible
  {
    public SC_Alarm() {}
    
    private Protocol _protocol = Protocol.SC_ALARM;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"protocol", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Protocol.SC_ALARM)]
    public Protocol protocol
    {
      get { return _protocol; }
      set { _protocol = value; }
    }
    private com.mango.protocol.msg.Alarm _alarm = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"alarm", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.mango.protocol.msg.Alarm alarm
    {
      get { return _alarm; }
      set { _alarm = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Alarm")]
  public partial class Alarm : global::ProtoBuf.IExtensible
  {
    public Alarm() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _flag = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"flag", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string flag
    {
      get { return _flag; }
      set { _flag = value; }
    }
    private int _type = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _sersor = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"sersor", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sersor
    {
      get { return _sersor; }
      set { _sersor = value; }
    }
    private long _altime = default(long);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"altime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long altime
    {
      get { return _altime; }
      set { _altime = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private string _peculiarnote = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"peculiarnote", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string peculiarnote
    {
      get { return _peculiarnote; }
      set { _peculiarnote = value; }
    }
    private long _dbtime = default(long);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"dbtime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long dbtime
    {
      get { return _dbtime; }
      set { _dbtime = value; }
    }
    private ALARM_STATE _state = ALARM_STATE.TEST;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(ALARM_STATE.TEST)]
    public ALARM_STATE state
    {
      get { return _state; }
      set { _state = value; }
    }
    private string _processuser = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"processuser", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string processuser
    {
      get { return _processuser; }
      set { _processuser = value; }
    }
    private string _processnote = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"processnote", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string processnote
    {
      get { return _processnote; }
      set { _processnote = value; }
    }
    private string _confirmnote = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"confirmnote", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string confirmnote
    {
      get { return _confirmnote; }
      set { _confirmnote = value; }
    }
    private long _processtime = default(long);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"processtime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long processtime
    {
      get { return _processtime; }
      set { _processtime = value; }
    }
    private string _confirmuser = "";
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"confirmuser", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string confirmuser
    {
      get { return _confirmuser; }
      set { _confirmuser = value; }
    }
    private long _confirmtime = default(long);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"confirmtime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long confirmtime
    {
      get { return _confirmtime; }
      set { _confirmtime = value; }
    }
    private int _record = default(int);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"record", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int record
    {
      get { return _record; }
      set { _record = value; }
    }
    private string _path = "";
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"path", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string path
    {
      get { return _path; }
      set { _path = value; }
    }
    private string _location = "";
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"location", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string location
    {
      get { return _location; }
      set { _location = value; }
    }
    private string _sersorname = "";
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"sersorname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sersorname
    {
      get { return _sersorname; }
      set { _sersorname = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}